version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "ruff"
      - dependency-name: "mypy"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "all"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: docker/
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "all"
    groups:
      all-dependencies:
        patterns:
          - "*"
