repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff-format

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/rafsaf/pyproject-tag-check
    rev: "1.0.0"
    hooks:
      - id: pyproject-tag-check
        always_run: true
        args:
          - https://github.com/rafsaf/ogion
