name: type-check
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"

jobs:
  type_check:
    strategy:
      matrix:
        check: ["ruff check", "mypy --check", "ruff format --check"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.2"
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev
        shell: bash

      - name: Run ${{ matrix.check }}
        run: |
          uv run ${{ matrix.check }} .
